version: '3.9'

services:
  auth-service:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
